"""Build every translated Markdown catalogue from the same records (Python 3.10+)."""

import argparse
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GROUPS = ("active", "retired", "experimental", "internal")


def read(path):
    return json.loads(path.read_text(encoding="utf-8"))


def relative(target, output):
    return Path(os.path.relpath(ROOT / target, output.parent)).as_posix()


def render(data, locale, languages, output):
    t = locale["ui"]
    link = lambda path: relative(path, output)
    sources = {s["id"]: s for s in data["sources"]}

    def refs(ids):
        return " · ".join(f'[{sid}]({sources[sid]["url"]})' for sid in ids)

    lines = ["<!-- Generated by scripts/build_catalog.py; edit data/ and i18n/. -->",
             f'# 🏆 {t["title"]}', "", t["intro"], "",
             f'**{t["updated"]}: {data["checked_on"]}** · {t["scope"]}', "",
             " · ".join(f'[{l["name"]}]({link("catalog/" + l["file"] + ".md")})' for l in languages), "",
             f'> {t["limits"]}', "", f'## 🧭 {t["navigation"]}', "",
             " · ".join(f'[{t[g]}](#{g})' for g in GROUPS) +
             " · " + " · ".join(f'[{t[k]}](#{k})' for k in ("tiers", "variants", "highlights", "history", "sources")), "",
             f'| {t["status"]} | # |', "| --- | ---: |"]
    for g, icon in zip(GROUPS, ("🟢", "🕰️", "🧪", "🔒")):
        count = sum(a["status"] == g for a in data["achievements"])
        lines.append(f'| {icon} [{t[g]}](#{g}) | {count} |')
    lines += ["", f'> {t["incident"]} {refs(["S08"])}', ""]
    for g, icon in zip(GROUPS, ("🟢", "🕰️", "🧪", "🔒")):
        lines += [f'<a id="{g}"></a>', f'## {icon} {t[g]}', "", t[g + "_note"], ""]
        for a in (a for a in data["achievements"] if a["status"] == g):
            lines += [f'<a id="{a["id"]}"></a>', f'### {a["name"]}', "",
                      f'<img src="{link(a["image"])}" width="96" alt="{a["name"]}">', "",
                      locale["descriptions"][a["id"]], ""]
            if a["tiers"]:
                numbers = " → ".join(str(x) for x in a["tiers"])
                lines += [f'**{t["tiers"]}:** {numbers} ({locale["units"][a["unit"]]}).', ""]
            if a.get("example"):
                lines += [f'[{t["example"]}]({a["example"]}) · {refs(a["sources"])}', ""]
            else:
                lines += [refs(a["sources"]), ""]
    lines += [f'<a id="tiers"></a>', f'## 🥇 {t["tiers"]}', "", t["tiers_note"], "",
              f'| {t["achievement"]} | {t["unit"]} | {t["default"]} | 🥉 x2 | 🥈 x3 | 🥇 x4 |',
              "| --- | --- | ---: | ---: | ---: | ---: |"]
    for a in data["achievements"]:
        if a["tiers"]:
            lines.append(f'| [{a["name"]}](#{a["id"]}) | {locale["units"][a["unit"]]} | ' + " | ".join(map(str, a["tiers"])) + " |")
    lines += ["", f'<details><summary>{t["gallery"]}</summary>', "",
              f'| {t["achievement"]} | {t["default"]} | 🥉 x2 | 🥈 x3 | 🥇 x4 |', "| --- | :---: | :---: | :---: | :---: |"]
    for a in data["achievements"]:
        if a.get("tier_images"):
            images = " | ".join(f'<img src="{link(p)}" width="72" alt="{a["name"]} {tier}">' for p, tier in zip(a["tier_images"], ("default", "bronze", "silver", "gold")))
            lines.append(f'| {a["name"]} | {images} |')
    lines += ["", "</details>", "", t["experimental_tiers"], "",
              f'| {t["achievement"]} | {t["default"]} | 🥉 x2 | 🥈 x3 | 🥇 x4 |', "| --- | ---: | ---: | ---: | ---: |"]
    for a in data["achievements"]:
        if a.get("reported_tiers"):
            lines.append(f'| {a["name"]} | ' + " | ".join(t["unknown"] if x is None else str(x) for x in a["reported_tiers"]) + " |")
    lines += ["", refs(["S15"]), "", f'<a id="variants"></a>', f'## 🎨 {t["variants"]}', "", t["variants_note"], "",
              f'[{t["settings"]}](https://github.com/settings/appearance)', "",
              f'| {t["achievement"]} | 👋 | 👋🏻 | 👋🏼 | 👋🏽 | 👋🏾 | 👋🏿 |', "| --- | :---: | :---: | :---: | :---: | :---: | :---: |"]
    for a in data["achievements"]:
        if a.get("variants"):
            lines.append(f'| {a["name"]} | ' + " | ".join(f'<img src="{link(p)}" width="56" alt="{a["name"]} {n}">' for n, p in enumerate([a["image"]] + a["variants"])) + " |")
    lines += ["", f'<a id="highlights"></a>', f'## ✨ {t["highlights"]}', "", t["highlights_note"], "",
              f'| {t["name"]} | {t["status"]} | {t["condition"]} | {t["sources"]} |', "| --- | --- | --- | --- |"]
    for h in data["highlights"]:
        lines.append(f'| **{h["name"]}** | {t[h["status"]]} | {locale["highlights"][h["id"]]} | {refs(h["sources"])} |')
    lines += ["", f'<a id="history"></a>', f'## 🗂️ {t["history"]}', "", t["history_note"], "",
              f'| {t["image"]} | 2021–2022 | {t["current_name"]} |', "| :---: | --- | --- |"]
    for h in data["legacy"]:
        lines.append(f'| <img src="{link(h["image"])}" width="64" alt="{h["name"]}"> | {h["name"]} | {h["current_name"]} |')
    lines += ["", refs(["S02", "S03", "S15"]), "", f'### {t["proxima_case"]}', "", t["proxima_note"], "",
              f'| {t["achievement"]} | {t["account"]} | UTC |', "| --- | --- | --- |"]
    for e in data["proxima_evidence"]:
        lines.append(f'| [{e["name"]}]({e["profile_url"]}) | @{e["account"]} | {e["unlocked_at_utc"]} |')
    lines += ["", t["inaccessible_note"], "", f'[{t["research"]}]({link("docs/research.ru.md" if locale["code"] == "ru" else "docs/research.en.md")})', "",
              f'<details><summary>{t["screenshots"]}</summary>', "",
              f'<img src="{link("assets/evidence/jakub-proxima-pioneer.png")}" width="360" alt="JakubOleksy — Proxima Pioneer">', "",
              f'<img src="{link("assets/evidence/jakub-proxima-staffshipper.png")}" width="360" alt="JakubOleksy — Proxima Staffshipper">', "",
              "</details>", "", f'<a id="sources"></a>', f'## 🔎 {t["sources"]}', "", t["sources_note"], ""]
    for s in data["sources"]:
        lines.append(f'- **{s["id"]}** — [{s["title"]}]({s["url"]}) · {t[s["kind"]]}')
    lines += ["", f'[{t["home"]}]({link("README.md")}) · [{t["contribute"]}]({link("CONTRIBUTING.md")})', ""]
    return "\n".join(lines)


def build(check=False):
    data = read(ROOT / "data/achievements.json")
    languages = read(ROOT / "i18n/languages.json")
    changed = []
    for lang in languages:
        locale = read(ROOT / f'i18n/{lang["code"]}.json')
        output = ROOT / f'catalog/{lang["file"]}.md'
        content = render(data, locale, languages, output)
        outputs = [(output, content)]
        if lang["code"] != "en":
            stub = ROOT / f'lang/{lang["file"]}.md'
            outputs.append((stub, f'# {locale["ui"]["title"]}\n\n[{locale["ui"]["open_catalog"]}](../catalog/{lang["file"]}.md)\n\n{locale["ui"]["moved"]}\n'))
        for path, value in outputs:
            if not path.exists() or path.read_text(encoding="utf-8") != value:
                changed.append(path.relative_to(ROOT).as_posix())
                if not check:
                    path.parent.mkdir(parents=True, exist_ok=True)
                    path.write_text(value, encoding="utf-8", newline="\n")
    if check and changed:
        raise SystemExit("Generated files out of date: " + ", ".join(changed))
    print(f'{len(languages)} languages; {len(data["achievements"])} achievements; ' + ("generated files are current" if check else f"{len(changed)} files updated"))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check generated files without writing")
    build(parser.parse_args().check)
